# Generated by Django 3.2.5 on 2022-05-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adssystem',
            name='jvm',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='adssystem',
            name='memory',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='adssystem',
            name='os',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='adssystem',
            name='storage',
            field=models.CharField(default='', max_length=600),
        ),
    ]
