# Generated by Django 3.2.5 on 2022-05-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwdTestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default='', max_length=100)),
                ('system_series', models.CharField(default='', max_length=100)),
                ('system_name', models.CharField(default='', max_length=300)),
                ('chips', models.IntegerField(default=1)),
                ('nodes', models.IntegerField(default=1)),
                ('total_cores', models.IntegerField(default=1)),
                ('l1_cache', models.CharField(default='', max_length=255)),
                ('l2_cache', models.CharField(default='', max_length=255)),
                ('l3_cache', models.CharField(default='', max_length=255)),
                ('memory', models.CharField(default='', max_length=255)),
                ('memory_amount', models.IntegerField(default=1)),
                ('memory_number', models.IntegerField(default=1)),
                ('storage_type', models.CharField(default='', max_length=100)),
                ('storage', models.CharField(default='', max_length=255)),
                ('os', models.CharField(default='', max_length=255)),
                ('file_system', models.CharField(default='', max_length=100)),
                ('jvm', models.CharField(default='', max_length=255)),
                ('result', models.FloatField()),
                ('suite_name', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_info', to='dim.dimcpu')),
                ('hw_avail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_info_hw_avail', to='dim.dimdate')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_info', to='dim.dimsuite')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_info', to='dim.dimsystem')),
                ('test_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_info_test_date', to='dim.dimdate')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_info', to='dim.dimvendor')),
            ],
            options={
                'db_table': 'dwd_test_info',
            },
        ),
        migrations.CreateModel(
            name='DwdSubmitInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default=1, max_length=100)),
                ('system_series', models.CharField(default='', max_length=100)),
                ('system_name', models.CharField(default='', max_length=300)),
                ('suite_name', models.CharField(default='', max_length=100)),
                ('submit_year', models.IntegerField(default=0)),
                ('submit_quarter', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_info', to='dim.dimsuite')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_info', to='dim.dimsystem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_info', to='dim.dimvendor')),
            ],
            options={
                'db_table': 'dwd_submit_info',
            },
        ),
    ]
