# Generated by Django 3.2.5 on 2022-05-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dwd', '0001_initial'),
        ('dim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TdmVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default='', max_length=300)),
                ('active_score', models.FloatField(default=0.0)),
                ('submit_ratio', models.FloatField(default=0.0)),
                ('prefer_cpu_type', models.CharField(default='', max_length=300)),
                ('cpu_sum_intel', models.IntegerField(default=0)),
                ('cpu_sum_amd', models.IntegerField(default=0)),
                ('cpu_sum_huawei', models.IntegerField(default=0)),
                ('cpu_sum_other', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdm_vendor', to='dim.dimvendor')),
            ],
            options={
                'db_table': 'tdm_vendor',
            },
        ),
        migrations.CreateModel(
            name='TdmSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='', max_length=300)),
                ('system_series_name', models.CharField(default='', max_length=300)),
                ('vendor_name', models.CharField(default='', max_length=100)),
                ('total_cores', models.IntegerField(default=0)),
                ('total_threads', models.IntegerField(default=0)),
                ('best_rank', models.IntegerField(default=0)),
                ('best_rank_suite_name', models.CharField(default='', max_length=300)),
                ('best_rank_total_num', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_rank_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdm_system', to='dim.dimsuite')),
                ('best_rank_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdm_system', to='dwd.dwdtestinfo')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdm_system', to='dim.dimsystem')),
                ('system_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdm_system', to='dim.dimsystemseries')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdm_system', to='dim.dimvendor')),
            ],
            options={
                'db_table': 'tdm_system',
            },
        ),
        migrations.CreateModel(
            name='TdmCpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.CharField(default='', max_length=300)),
                ('cpu_vendor', models.CharField(default='', max_length=100)),
                ('cpu_ghz', models.FloatField(default=0.0)),
                ('max_ghz', models.FloatField(default=0.0)),
                ('cores', models.IntegerField(default=1)),
                ('threads_per_core', models.IntegerField(default=1)),
                ('is_turbo', models.IntegerField(default=0)),
                ('logical_cpus', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdm_cpu', to='dim.dimcpu')),
            ],
            options={
                'db_table': 'tdm_cpu',
            },
        ),
    ]
