# Generated by Django 3.2.5 on 2022-05-20 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dim', '0001_initial'),
        ('tdm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdmsystem',
            name='vendor_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tdmsystem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdm_system', to='dim.dimvendor'),
        ),
    ]
