# Generated by Django 3.2.5 on 2022-05-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dim', '0001_initial'),
        ('dwd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwsVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(default='', max_length=300)),
                ('submit_sum_1y', models.IntegerField(default=0)),
                ('submit_sum_1q', models.IntegerField(default=0)),
                ('submit_sum', models.IntegerField(default=0)),
                ('first_submit_date', models.DateField()),
                ('last_submit_date', models.DateField()),
                ('system_sum', models.IntegerField(default=0)),
                ('system_series_sum', models.IntegerField(default=0)),
                ('nt_1y', models.IntegerField(default=0)),
                ('nt_1q', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dws_vendor', to='dim.dimvendor')),
            ],
            options={
                'db_table': 'dws_vendor',
            },
        ),
        migrations.CreateModel(
            name='DwsBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(default='', max_length=300)),
                ('vendor_name', models.CharField(default='', max_length=300)),
                ('system_name', models.CharField(default='', max_length=300)),
                ('cpu_type', models.CharField(default='', max_length=300)),
                ('rank_level', models.IntegerField(default=0)),
                ('total_test', models.IntegerField(default=0)),
                ('test_date_value', models.DateField()),
                ('time_level', models.CharField(default='', max_length=10)),
                ('result', models.FloatField()),
                ('url_suffix', models.CharField(default='', max_length=600)),
                ('full_url', models.CharField(default='', max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hw_avail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dws_benchmark_hw_avail', to='dim.dimdate')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dws_benchmark', to='dim.dimsuite')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dws_benchmark', to='dim.dimsystem')),
                ('test_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dws_benchmark_test_date', to='dim.dimdate')),
                ('test_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dws_benchmark', to='dwd.dwdtestinfo')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dws_benchmark', to='dim.dimvendor')),
            ],
            options={
                'db_table': 'dws_benchmark',
            },
        ),
    ]
