# Generated by Django 3.2.5 on 2022-05-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwsvendor',
            name='submit_sum_y',
            field=models.IntegerField(default=0),
        ),
    ]
