# Generated by Django 3.2.5 on 2022-05-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dws', '0002_dwsvendor_submit_sum_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dwsvendor',
            name='submit_sum_y',
        ),
    ]
