# Generated by Django 3.2.5 on 2022-05-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OdsSpecModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite', models.CharField(default='', max_length=100, verbose_name='套件名称')),
                ('hw_vendor', models.CharField(default='', max_length=100, verbose_name='服务器厂商')),
                ('system_series', models.CharField(default='', max_length=100, verbose_name='服务器系列')),
                ('result', models.FloatField(default=0.0, verbose_name='得分')),
                ('cpu_vendor', models.CharField(default='', max_length=100, verbose_name='cpu 厂商')),
                ('cpu_name', models.CharField(default='', max_length=400, verbose_name='cpu 名字')),
                ('cpu_ghz', models.FloatField(default=0.0, verbose_name='CPU GHz')),
                ('max_ghz', models.FloatField(default=0.0, verbose_name='CPU Max GHz')),
                ('threads_per_core', models.IntegerField(default=1, verbose_name='每个核的线程数')),
                ('cores_per_chip', models.IntegerField(default=1, verbose_name='每个cpu的核数')),
                ('chips', models.IntegerField(default=1, verbose_name='芯片数')),
                ('nodes', models.IntegerField(default=1, verbose_name='节点数')),
                ('total_cores', models.IntegerField(default=1, verbose_name='总核数')),
                ('l1_cache', models.CharField(default='', max_length=600, verbose_name='一级缓存')),
                ('l2_cache', models.CharField(default='', max_length=600, verbose_name='二级缓存')),
                ('l3_cache', models.CharField(default='', max_length=600, verbose_name='三级缓存')),
                ('memory', models.CharField(default='', max_length=600, verbose_name='内存信息')),
                ('memory_amount', models.IntegerField(default=1, verbose_name='内存总量')),
                ('memory_number', models.IntegerField(default=1, verbose_name='内存条数量')),
                ('storage_type', models.CharField(default='', max_length=100, verbose_name='硬盘类型')),
                ('storage', models.CharField(default='', max_length=600, verbose_name='硬盘信息')),
                ('os', models.CharField(default='', max_length=600, verbose_name='OS信息')),
                ('file_system', models.CharField(default='', max_length=100, verbose_name='文件系统')),
                ('jvm', models.CharField(default='', max_length=600, verbose_name='JVM信息')),
                ('url_suffix', models.CharField(default='', max_length=400, verbose_name='url后缀')),
                ('test_date', models.DateField(verbose_name='测试日期')),
                ('hw_avail', models.DateField(verbose_name='硬件发布时间')),
                ('submit_quarter', models.IntegerField(default=1, verbose_name='提交时间所在季度')),
                ('submit_year', models.IntegerField(default=0, verbose_name='提交时间所在年份')),
                ('full_url', models.CharField(default='', max_length=400, verbose_name='URL链接')),
            ],
            options={
                'verbose_name': 'spec',
                'verbose_name_plural': 'spec',
                'db_table': 'ods_spec',
            },
        ),
    ]
